
@productId = 10
@clientId = {{profile.response.body.profile.id}}

@baseUrl = http://localhost:3333

# Client
# @name register
POST {{baseUrl}}/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.do1e@example.com",
  "password": "password"
}

###

# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password"
}

###

# @name change_password
PATCH {{baseUrl}}/change-password
Content-Type: application/json

{
  "password": "newpassword2"
}

###

# @name profile
GET {{baseUrl}}/profile

###

# @name update_profile
PUT {{baseUrl}}/profile
Content-Type: application/json

{
  "name": "John Doe Updated"
}

###

# @name toggle_favorite_product
POST {{baseUrl}}/product/{{productId}}/favorite

###

# @name delete_user
DELETE {{baseUrl}}/profile

###

# Admin

# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "admin@aiqfome.com",
  "password": "password"
}

###

# @name update_client_data
PATCH  {{baseUrl}}/client/{{clientId}}/change-password
Content-Type: application/json

{
  "password": "newpassword123"
}

###

# @name update_client_data
PUT  {{baseUrl}}/client/{{clientId}}
Content-Type: application/json

{
  "name": "John Doe Updated 123"
}

###

# @name get_client_by_id
GET {{baseUrl}}/client/{{clientId}}

###
{
  "name": "John Doe Updated 123"
}

###

# @name delete_client
DELETE {{baseUrl}}/client/{{clientId}}

###

