version: '3.8'

services:
  postgres:
    image: postgres:17.4
    restart: always
    shm_size: 128mb
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aiqfome-client
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
