version: '3.8'

services:
  postgres:
    image: postgres:17.4
    restart: always
    shm_size: 128mb
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aiqfome-client
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data

  aiqfome-app:
    build:
      context: .
      dockerfile: docker/builders/Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/aiqfome-client?schema=public
      - PORT=3000
      - JWT_SECRET=SECRET
    volumes:
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma
