FROM node:22.11.0-alpine

RUN npm install -g pnpm

WORKDIR /usr/src/app

COPY package.json ./

RUN pnpm install

COPY tsconfig.json ./


COPY src ./src
COPY prisma ./prisma

RUN pnpm prisma:type

EXPOSE 3333

CMD ["pnpm", "start:dev"]
