FROM node:22.11.0

ARG PORT=3333

RUN npm install -g pnpm

WORKDIR /usr/src/app

COPY package.json ./
COPY pnpm-lock.yaml ./

COPY tsconfig.json ./

COPY src ./src
COPY prisma ./prisma

RUN pnpm install

RUN pnpm prisma:type

EXPOSE ${PORT}

CMD ["pnpm", "dev"]
